name: Deploy to Naver Cloud

on:
  push:
    branches: [develop, master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Deploy ncloud
        uses: appleboy/ssh-action@master
        id: deploy-prod
        with:
          host: ${{secrets.NCLOUD_SERVER_IP}}
          username: ${{secrets.NCLOUD_SERVER_USER}}
          password: ${{secrets.NCLOUD_SERVER_PW}}
          port: ${{secrets.NCLOUD_SERVER_PORT}}
          script: |
            cd doyouhave/Backend/
            chmod +x deploy.sh
            ./deploy.sh
